### ISSUE TITLE
BackEnd Database 추가

### ISSUE THREAD

**Issue by sckimynwa** [pancakestudio/smallsnu_backend#1]
frontend에서 계속해서 반복문을 돌리면서 빌딩넘버와 위치를 계산하는 것이 비효율적으로 보여서
backend database에 건물코드와, 건물의 중심좌표정보를 넣어주시면 좋겠습니다!!

Example:
{
    ...,
   code : "1",
   location : [37.235, 128.111],
   ....
}

**Comment by Dorvin** [comment]
기능 추가했습니다!

**Comment by Dorvin** [comment]
닫겠습니다!
